### ISSUE TITLE
Collected notes/issues

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#157] opened 2022-05-07 21:45 UTC
### **Uncategorized:**
**ITEM 1:** Login screen cleanup. I keep writing custom ones for clients that are extremely basic, but nice looking.

**ITEM 2:** File editor, autocompleting a snippet that starts with "GS.", when applied, ends up starting with "GS.GS."

**ITEM 3:** Dot.js module, add new token for easy URI encoding, converting "{{%" to "encodeURIComponent(".

**ITEM 4:** Utility, build a date format function (see: 006-utl-format.js).

**ITEM 5:** Basic Envelope element tutorials.

**ITEM 6:** GS-listbox, general cleanup.

**ITEM 7:** All gs controls, handling empty values.

**ITEM 8:** GS-dialog, template with QS before opening, need to avoid templating template elements.

**ITEM 9:** GS-select, "inline" attribute.

**ITEM 10:** GS-text, max length, type in to max length and hit tab (double tabs, because we cause a tab at the last char).

**ITEM 11:** GS-option text control inside option intercepts space bar.

### **Form Items:**

**ITEM 12:** GS-form, fix documentation, it appears to be a duplicate of gs-folder.

**ITEM 13:** GS-form, add an attribute to prevent all re-renders after updates.

**ITEM 14:** GS-form, verify that columns being updated exist, put an appropriate error in when the form attempts to update a column that isn't in it's column list.

**ITEM 15:** GS-form, save-while-typing attribute, selects all text in inner gs-ace sometimes.

### **GS-combo Items:**

**ITEM 16:** GS-combo, "inline" attribute not working.

**ITEM 17:** GS-combo, scroll by one record at a time.

**ITEM 18:** GS-combo, when cleared out, send null to update form, not empty string (test clearing an integer column).

**ITEM 19:** GS-combo, slow query, need to dropdown immediately and show something, even if only loader.

**ITEM 20:** GS-combo, .column() method, accept a column number and template that gs-cell and return the content.

**ITEM 21:** GS-combo, wont autocomplete if typing in all caps.

**ITEM 22:** GS-combo, timekeeping project combo won't allow me to set my own capitalization, it keeps getting overridden by autocomplete suggestions.

**ITEM 23:** GS-combo, Choosing something from a combo box jumps the scroll up to the top.

### **GS-table Items:**

**ITEM 24:** GS-table, add a "getRecordJSON" method. It accepts a record number, and returns a JSON object.

**ITEM 25:** GS-table, recalculate hud size on window resize.

**ITEM 26:** GS-table, tab into insert record.

**ITEM 27:** GS-table, when the header cell has "hidden" attribute, hide by default.

**ITEM 28:** GS-table, no-horizontal-overscroll cuts off last column when too much.

**ITEM 29:** GS-table, animate scroll, (need to give an accurate impression of distance moved) (but, always end at a record).

**ITEM 30:** GS-table, use dataLedger for initialize select calls? This way, if tables are rapidly destroyed/created, we don't have a bunch of repeated select calls?

**ITEM 31:** GS-table, if you hide all columns, you can't unhide columns (we need to add a context menu to the viewport).

**ITEM 32:** GS-table, allows multiple updates in the air at the same time for the same cell, causing update conflicts with self (slow network).

**ITEM 33:** GS-table, refreshing a gs-table that is loading data should interrupt the current refresh.

**Comment by crosstocci** [comment] 2023-07-05 20:16
ITEM 1: Login screen has been cleaned up.
ITEM 2: "GS." snippets fixed.
ITEM 3: "{{%" to "encodeURIComponent(" added.
ITEM 4: Add GS.to_char
ITEM 5: Documentation recently redone.
ITEM 6: Unclear what needs to be cleaned up in the gs-listbox
ITEM 7: Fixed gs-time, the other have been update since this issue was created
ITEM 8: GS-dialog, is now templated with QS before opening, avoiding internal template tabs
ITEM 9: GS-select, "inline" attribute added.
Item 10 the standard "maxlength" attribute does not autotab. Use that if you want to tab yourself. Only our "max-length" attribute autotabs. I don't think autotab makes sense at all unless a customer specificly requests it.
ITEM 11: buttons no longer interpret spacebar as click unless the element itself is the target of the keydown event.
Item 12 Documentation is complete.
ITEM 13: added "suspend-render-after-update" attribute
ITEM 14: This already has a good error from the database.
ITEM 15: save-while-typing was selection the whole gs-ace sometimes. fixed.
ITEM 16: GS-combo, "inline" attribute added.
ITEM 17: This is gonna be fixed with ITEM 29.
ITEM 18: GS-combo, added allow-empty="null value" functionality
ITEM 19: Added loader inside combo dropdown when records have not finished returning
ITEM 20: Added number support to gs-combo.column()
ITEMS 21/22: GS-combo, these two items don't make sense. Currently it sets to a capitalization that exists. If none exists it leaves it. It has always worked like this. If you want something else open an issue and supply a good set of rules to handle all the possible situations.
ITEM 23: Can't reproduce, tried in gs-table. Not sure what was scrolling either as you didn't specify.
ITEM 24: Added method and documented.
ITEM 25: GS-table, recalculate hud size on window resize.
ITEM 26: GS-table, you can tab into insert record.
ITEM 27: GS-table, when a header cell has "hidden" attribute, it will be hidden by default.
ITEM 28: GS-table, no-x-overscroll was cutting off last column when too much, I added a pixel to the width and it seems to have solved it.
ITEM 30: This seems like overkill. The gs-table will want to always have the latest records when it is loaded and it is unlikely to have multiple load the same data at the same time. Ignored.
ITEM 31: Added context menu to viewport and record selectors


Closing this issue and opening a new one with the remaining three issues.

**Closed as completed by crosstocci** 2023-07-05 20:16 UTC
